import type { DashboardController } from '@/features/dashboard/hooks/use-dashboard-controller';

export type SettingsPageProps = Pick<
  DashboardController,
  | 'appState'
  | 'canStart'
  | 'clearProfileDocuments'
  | 'consent'
  | 'dataActionNotice'
  | 'deleteAllLocalData'
  | 'exportAllData'
  | 'ollama'
  | 'ollamaCancelPull'
  | 'ollamaPullModel'
  | 'ollamaRefresh'
  | 'overlayPreferences'
  | 'savePreferences'
  | 'setConsentField'
  | 'setOverlayPreference'
  | 'setSavePreference'
  | 'sideOverlayVisible'
  | 'startSession'
  | 'stt'
  | 'sttCancelDownload'
  | 'sttDownloadModel'
  | 'sttRefresh'
  | 'stopSession'
  | 'toggleShareSafeMode'
  | 'toggleOverlaySection'
  | 'topOverlayVisible'
>;
