import type {
  KnowledgeRecord,
  PersonRecord,
  ProjectRecord,
  ReviewRecord,
  SessionRecord,
  TemplateRecord,
} from '@/features/dashboard/lib/workspace-types';

export const sessionSeeds: SessionRecord[] = [
  {
    id: 'session-company-a-casual',
    title: '株式会社A カジュアル面談',
    type: '面談',
    typeTone: 'green',
    dateLabel: '今日 14:00',
    startAt: '2024-05-21T14:00:00+09:00',
    partner: '田中さん',
    location: 'Google Meet',
    platform: 'Google Meet',
    durationMinutes: 60,
    recording: '録画中',
    recordingTone: 'blue',
    peopleIds: ['person-tanaka-ichiro'],
    projectIds: ['project-company-a-consulting'],
    reviewId: 'review-catalyst',
    status: '完了',
    statusTone: 'green',
    memo: '志望動機と今後のキャリアについて深掘り',
  },
  {
    id: 'session-lab-meeting',
    title: '研究室ミーティング',
    type: '会議',
    typeTone: 'green',
    dateLabel: '今日 16:00',
    startAt: '2024-05-21T16:00:00+09:00',
    partner: '研究室',
    location: '302会議室',
    platform: 'オフライン',
    durationMinutes: 60,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: ['person-yamamoto-kenta'],
    projectIds: ['project-new-business'],
    status: '予定',
    statusTone: 'blue',
    memo: '進捗共有と今後の方針確認',
  },
  {
    id: 'session-gd-practice',
    title: 'GD練習（模擬）',
    type: 'GD',
    typeTone: 'violet',
    dateLabel: '今日 18:00',
    startAt: '2024-05-21T18:00:00+09:00',
    partner: '就活仲間',
    location: 'オンライン',
    platform: 'オンライン',
    durationMinutes: 90,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: ['person-suzuki-aoi'],
    projectIds: ['project-casual-bar'],
    status: '予定',
    statusTone: 'blue',
    memo: 'テーマ: 新しい教育サービスの提案',
  },
  {
    id: 'session-company-b-interview',
    title: '株式会社B 一次面接',
    type: '面接',
    typeTone: 'orange',
    dateLabel: '2024/05/20 10:00',
    startAt: '2024-05-20T10:00:00+09:00',
    partner: '人事部',
    location: 'Zoom',
    platform: 'Zoom',
    durationMinutes: 45,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: ['person-tanaka-ichiro'],
    projectIds: ['project-casual-bar'],
    reviewId: 'review-sales-innovation',
    status: '完了',
    statusTone: 'green',
    memo: '自己紹介、ガクチカ、志望動機',
  },
  {
    id: 'session-senior-1on1',
    title: '先輩との1on1',
    type: '1on1',
    typeTone: 'gold',
    dateLabel: '2024/05/18 15:30',
    startAt: '2024-05-18T15:30:00+09:00',
    partner: '佐藤さん',
    location: 'カフェ',
    platform: '対面',
    durationMinutes: 30,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: ['person-sato-hanako'],
    projectIds: ['project-new-business'],
    status: '完了',
    statusTone: 'green',
    memo: 'キャリアの悩み相談とアドバイス',
  },
  {
    id: 'session-company-c-final',
    title: '株式会社C 最終面接',
    type: '面接',
    typeTone: 'orange',
    dateLabel: '2024/05/15 14:00',
    startAt: '2024-05-15T14:00:00+09:00',
    partner: '役員',
    location: 'Google Meet',
    platform: 'Google Meet',
    durationMinutes: 60,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: ['person-takahashi-taro'],
    projectIds: ['project-company-a-consulting'],
    status: '完了',
    statusTone: 'green',
    memo: '逆質問、入社後のミッションについて',
  },
  {
    id: 'session-toeic-day3',
    title: 'TOEIC対策授業 Day3',
    type: '授業',
    typeTone: 'violet',
    dateLabel: '2024/05/12 09:00',
    startAt: '2024-05-12T09:00:00+09:00',
    partner: 'オンライン授業',
    location: 'Zoom',
    platform: 'Zoom',
    durationMinutes: 90,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: [],
    projectIds: [],
    status: '完了',
    statusTone: 'green',
    memo: 'Part 5、6の演習と解説',
  },
  {
    id: 'session-intern-briefing',
    title: 'インターン選考説明会',
    type: 'その他',
    typeTone: 'gray',
    dateLabel: '2024/05/10 11:00',
    startAt: '2024-05-10T11:00:00+09:00',
    partner: '株式会社D',
    location: 'オンライン',
    platform: 'オンライン',
    durationMinutes: 60,
    recording: '',
    recordingTone: 'neutral',
    peopleIds: [],
    projectIds: [],
    status: '完了',
    statusTone: 'green',
    memo: 'インターンの概要と選考フロー',
  },
];

export const peopleSeeds: PersonRecord[] = [
  {
    id: 'person-tanaka-ichiro',
    name: '田中 一郎',
    role: '株式会社A 人事部 採用担当',
    shortRole: '面談官・採用担当',
    mail: 'ichiro.tanaka@company-a.com',
    updatedAt: '2024/05/12',
    lastContactLabel: '2024/05/12（面談）',
    profile: [
      '株式会社Aの新卒採用を担当。理系採用の一次面談・最終面談を担当している。',
      '学生の価値観や志向性を重視したカルチャーフィットを大切にしており、研究内容やチームでの工夫、再現性のある取り組みを評価する傾向。',
    ],
    checks: [
      'チーム配属後のオンボーディングの進め方は？',
      '評価で特に重視する行動やアウトプットは？',
      '入社後に活躍している人の共通点は？',
      '御社でのキャリアパスの具体例について',
    ],
    memo: [
      '研究テーマに興味を持ってくれた。特に〇〇の部分を評価。',
      '「チームでの成果の再現性」を繰り返し確認された。',
      '逆質問で「若手の裁量」について聞くと良い反応。',
    ],
    history: [
      {
        id: 'person-history-1',
        title: '一次面談',
        type: '面談',
        date: '2024/05/12 14:00',
        duration: '30分',
      },
      {
        id: 'person-history-2',
        title: 'ES提出前相談',
        type: '面談',
        date: '2024/04/28 15:30',
        duration: '30分',
      },
      {
        id: 'person-history-3',
        title: 'インターン面談',
        type: '面談',
        date: '2024/03/15 16:00',
        duration: '30分',
      },
    ],
  },
  {
    id: 'person-sato-hanako',
    name: '佐藤 花子',
    role: '事業開発部 エンジニア',
    shortRole: '社員・先輩',
    mail: 'hanako.sato@company-a.com',
    updatedAt: '2024/05/08',
    lastContactLabel: '2024/05/08（1on1）',
    profile: [
      '現場での意思決定や、若手がどう裁量を持つかに関心が高い。',
      '技術の深さだけでなく、チームでどう価値を出したかを重視して会話するタイプ。',
    ],
    checks: [
      '若手でも設計に入れる範囲は？',
      '失敗から学んだことをどう評価する？',
    ],
    memo: ['実装の工夫だけでなく、周囲との連携も伝えると刺さりやすい。'],
    history: [],
  },
  {
    id: 'person-yamamoto-kenta',
    name: '山本 健太',
    role: '研究室 先輩',
    shortRole: '社員・先輩',
    mail: 'kenta.yamamoto@example.com',
    updatedAt: '2024/05/05',
    lastContactLabel: '2024/05/05（会議）',
    profile: ['議論の整理役として頼れる存在。研究の相談相手でもある。'],
    checks: ['次回までに確認したい実験条件は何か？'],
    memo: ['結論を先に出すと議論が進みやすい。'],
    history: [],
  },
  {
    id: 'person-suzuki-aoi',
    name: '鈴木 葵',
    role: '就活エージェント',
    shortRole: 'その他',
    mail: 'aoi.suzuki@career.jp',
    updatedAt: '2024/04/28',
    lastContactLabel: '2024/04/28（面談）',
    profile: ['面接準備や企業比較の壁打ち相手。'],
    checks: ['次に見ておくべき企業群は？'],
    memo: ['比較軸を増やすと企業理解が深まる。'],
    history: [],
  },
  {
    id: 'person-takahashi-taro',
    name: '高橋 太郎',
    role: '株式会社C 役員',
    shortRole: '面談官・採用担当',
    mail: 'taro.takahashi@company-c.com',
    updatedAt: '2024/04/20',
    lastContactLabel: '2024/04/20（面接）',
    profile: ['事業視点から成果の再現性を問うタイプ。'],
    checks: ['入社後に期待される役割は？'],
    memo: ['数字と意思決定理由をセットで出すと良い。'],
    history: [],
  },
  {
    id: 'person-ito-sho',
    name: '伊藤 翔',
    role: 'プロダクトマネージャー',
    shortRole: 'メンバー・同僚',
    mail: 'sho.ito@product.example',
    updatedAt: '2024/04/12',
    lastContactLabel: '2024/04/12（会議）',
    profile: ['プロダクト視点で論点整理に長けている。'],
    checks: ['次回までの仕様確認ポイントは？'],
    memo: ['ユーザー価値の観点から話すと進みやすい。'],
    history: [],
  },
  {
    id: 'person-nakamura-misaki',
    name: '中村 美咲',
    role: 'データサイエンティスト',
    shortRole: 'メンバー・同僚',
    mail: 'misaki.nakamura@lab.example',
    updatedAt: '2024/04/10',
    lastContactLabel: '2024/04/10（会議）',
    profile: ['仮説検証の粒度に厳密。定量観点に強い。'],
    checks: ['検証ログの残し方は十分か？'],
    memo: ['数値の定義を先にそろえると話が速い。'],
    history: [],
  },
  {
    id: 'person-watanabe-yuto',
    name: '渡辺 悠斗',
    role: '営業部 リーダー',
    shortRole: 'その他',
    mail: 'yuto.watanabe@sales.example',
    updatedAt: '2024/04/05',
    lastContactLabel: '2024/04/05（その他）',
    profile: ['現場ニーズや顧客課題のヒントをくれる。'],
    checks: ['顧客が今困っていることは何か？'],
    memo: ['現場の言葉を引き出すと具体性が上がる。'],
    history: [],
  },
];

export const projectSeeds: ProjectRecord[] = [
  {
    id: 'project-casual-bar',
    title: '株式会社カジュアル酒場',
    category: '企業',
    subtitle: '居酒屋業 / 飲食サービス',
    progress: 60,
    sessions: 12,
    issues: 8,
    updatedAt: '今日 14:00',
    tone: 'violet',
    icon: 'company',
    statusLabel: 'アクティブ',
    overview:
      '関東エリアを中心に展開する居酒屋チェーン。カジュアルな雰囲気とリーズナブルな価格帯で、20〜40代の会社員を中心に支持を集めている。',
    linkedSessions: [
      {
        id: 'pl-1',
        title: '研究室ミーティング',
        type: '会議',
        date: '今日 16:00',
      },
      { id: 'pl-2', title: 'GD練習（模擬）', type: 'GD', date: '昨日 18:00' },
      {
        id: 'pl-3',
        title: '株式会社カジュアル酒場 定例MTG',
        type: '会議',
        date: '2024/05/15',
      },
    ],
    points: [
      '新規出店計画: 2024年内に5店舗の出店を予定',
      '人材採用・教育の強化が急務',
      '原材料費の高騰に対するコスト最適化が課題',
      'デジタルマーケティングの強化で集客向上を目指す',
    ],
    actions: [
      {
        id: 'pa-1',
        title: '新店舗出店計画の詳細検討',
        dueDate: '2024/05/20',
        priority: '高',
      },
      {
        id: 'pa-2',
        title: '採用戦略の見直し提案',
        dueDate: '2024/05/22',
        priority: '中',
      },
      {
        id: 'pa-3',
        title: 'コスト最適化施策の提案資料作成',
        dueDate: '2024/05/25',
        priority: '中',
      },
    ],
    connections: [
      '最終打ち合わせ: 今日 14:00（田中さん / Google Meet）',
      '担当者: 田中 太郎（代表取締役）',
      '関係期間: 2024年3月〜現在（3ヶ月）',
      '主な役割: 経営課題の整理・戦略支援',
    ],
  },
  {
    id: 'project-new-business',
    title: '新規事業プロジェクト',
    category: 'プロジェクト',
    subtitle: '新規事業開発',
    progress: 70,
    sessions: 15,
    issues: 10,
    updatedAt: '今日 09:30',
    tone: 'green',
    icon: 'chart',
    statusLabel: '進行中',
    overview: '仮説検証を高速に回しながら、新規サービスの構想を磨いている。 ',
    linkedSessions: [],
    points: ['仮説の優先順位を毎週更新する', 'ユーザー課題の深掘りを継続する'],
    actions: [],
    connections: ['担当: User'],
  },
  {
    id: 'project-company-a-consulting',
    title: '株式会社Aコンサルティング',
    category: '企業',
    subtitle: '経営コンサルティング',
    progress: 40,
    sessions: 9,
    issues: 6,
    updatedAt: '昨日 18:45',
    tone: 'violet',
    icon: 'company',
    statusLabel: 'アクティブ',
    overview: '経営課題と現場課題の橋渡し支援を行う案件。',
    linkedSessions: [],
    points: ['意思決定者の論点を先に把握する'],
    actions: [],
    connections: ['担当: User'],
  },
];

export const reviewSeeds: ReviewRecord[] = [
  {
    id: 'review-sales-innovation',
    title: '株式会社セールス・イノベーション',
    date: '2024/05/20',
    meta: '2024/05/20 14:00 - 15:00',
    type: '面談',
    summary: [
      '課題ヒアリングで相手の本質的なニーズを深掘りできた。',
      '自社サービスの価値を具体例を交えて分かりやすく伝えられた。',
      'クロージングに向けて自然な流れで次のステップを提案できた。',
    ],
    transcript: [
      '相手: 現場定着がうまく進まず、営業プロセスが属人化しています。',
      'あなた: 定着の阻害要因を運用面とツール面に分けて整理しましょう。',
      '相手: その切り分けは分かりやすいです。現場教育も課題です。',
    ],
    insights: [
      '現在、営業プロセスの属人化が課題になっている。',
      'SFAの導入は進めているが、現場定着に苦戦している。',
      '来期予算での投資検討を進めており、6月中の判断を目指している。',
    ],
    improvements: [
      '冒頭のアイスブレイクがやや長く、本題への導入に時間がかかった。',
      '競合比較の説明で、当社独自の強みの訴求が弱かった。',
      '相手の懸念点に対する具体的な解決策の提示が不足していた。',
    ],
    memo: [
      '現場定着の成功事例を次回用に必ず準備する。',
      'ROIシミュレーションを数値で示せる形にして持参する。',
    ],
    actions: [
      {
        id: 'ra-1',
        title: '提案資料をカスタマイズして再送する',
        owner: '田中 一郎',
        date: '2024/05/22',
      },
      {
        id: 'ra-2',
        title: '事例集（同業界）の追加資料を作成する',
        owner: '佐藤 花子',
        date: '2024/05/24',
      },
      {
        id: 'ra-3',
        title: '次回ミーティングの日程調整を行う',
        owner: '田中 一郎',
        date: '2024/05/24',
      },
    ],
  },
  {
    id: 'review-catalyst',
    title: '株式会社カタリスト',
    date: '2024/05/18',
    meta: '昨日 10:30 / 45分 / Zoom',
    type: '面談',
    summary: ['次回に向けた論点整理ができた。'],
    transcript: ['まだ要約のみ保存。'],
    insights: ['比較軸の明確化が必要。'],
    improvements: ['導入で相手の期待値確認を増やしたい。'],
    memo: ['次回は数字を一つ足す。'],
    actions: [
      {
        id: 'ra-4',
        title: '比較表を更新する',
        owner: 'User',
        date: '2024/05/19',
      },
    ],
  },
];

export const knowledgeSeeds: KnowledgeRecord[] = [
  {
    id: 'knowledge-self-summary',
    title: '自己分析まとめ',
    tag: '自己分析',
    updatedAt: '2024/05/10',
    source: 'manual',
    content: [
      '価値観として「相手理解」「改善の積み重ね」「再現性」を重視している。',
      '話すときは成果だけでなく、意思決定の理由と学びまで整理して伝える。',
      '面談や会議では、相手の意図を汲み取って補助線を引く役回りが強み。',
    ],
  },
  {
    id: 'knowledge-usj',
    title: 'USJでの改善経験',
    tag: '経験・エピソード',
    updatedAt: '2024/05/08',
    source: 'manual',
    content: [
      'アルバイトリーダーとして、待ち時間の見える化を提案した。',
      '課題設定と仮説検証を繰り返し、満足度向上を実現した。',
      '面談では再現性・数値・周囲との連携まで話せるよう整理している。',
    ],
  },
  {
    id: 'knowledge-research',
    title: '研究での仮説検証経験',
    tag: '経験・エピソード',
    updatedAt: '2024/05/06',
    source: 'manual',
    content: [
      '仮説の精度よりも、検証サイクルを短く回す設計を重視していた。',
      '定量だけでなく、現場観察のメモを意思決定に組み込んだ。',
      '不確実性が高い場面でも、次に試す打ち手を切らさない進め方を意識した。',
    ],
  },
  {
    id: 'knowledge-team-role',
    title: 'チーム開発での役割',
    tag: '経験・エピソード',
    updatedAt: '2024/05/07',
    source: 'manual',
    content: [
      '議論が拡散したときに論点整理と役割分担を引き受けることが多い。',
      '仕様の抜け漏れを埋めるために、要件の前提を言語化して共有した。',
      '実装だけでなく、他メンバーが動きやすい資料化も担っていた。',
    ],
  },
];

export const templateSeeds: TemplateRecord[] = [
  {
    id: 'template-interview-brief',
    title: '面接準備ブリーフ',
    description:
      '相手や企業情報をもとに、事前に知っておくべき情報を整理します。',
    tag: '事前準備',
    icon: 'doc',
    tone: 'blue',
    updatedAt: '2024/05/20',
    body: ['目的', '相手の背景', '確認したいこと', '話す候補', '注意点'],
  },
  {
    id: 'template-expected-questions',
    title: '想定質問集',
    description:
      'よく聞かれる質問への回答を事前に準備し、面接対策を強化します。',
    tag: '想定質問',
    icon: 'question',
    tone: 'slate',
    updatedAt: '2024/05/19',
    body: ['質問', '結論', '背景', '具体例', '学び'],
  },
  {
    id: 'template-self-intro',
    title: '自己紹介（30秒）',
    description: '自己紹介の骨子をもとに、30秒の自己紹介を作成します。',
    tag: '事前準備',
    icon: 'chat',
    tone: 'green',
    updatedAt: '2024/05/18',
    body: ['肩書き', '現在地', '強み', '締め'],
  },
  {
    id: 'template-reverse-question',
    title: '逆質問リスト',
    description: '面接官が聞きそうな逆質問をシーン別に用意します。',
    tag: '想定質問',
    icon: 'list',
    tone: 'orange',
    updatedAt: '2024/05/17',
    body: ['働き方', '評価', '配属', 'チーム文化'],
  },
];

export function createSeedWorkspace() {
  return {
    sessions: sessionSeeds,
    people: peopleSeeds,
    projects: projectSeeds,
    reviews: reviewSeeds,
    knowledgeItems: knowledgeSeeds,
    templates: templateSeeds,
  };
}

export function buildImportedKnowledgeContent(title: string, content?: string) {
  if (content && content.trim().length > 0) {
    return content
      .split(/\n+/)
      .map((line) => line.trim())
      .filter(Boolean)
      .slice(0, 12);
  }

  const fallbackMap: Record<string, string[]> = {
    values: [
      '大事にしている価値観を短く伝えられるように整理したメモです。',
      '面談では判断基準や動機の軸として引用できるようにしてあります。',
      '相手の質問に合わせて、具体例と一緒に話す前提でまとめています。',
    ],
    projects: [
      '関わったプロジェクトと担当範囲を一覧で振り返れるように整理しています。',
      '成果だけでなく、難しさや工夫した点まで追記できる形を想定しています。',
      '会話では相手の関心に応じて、詳細を深掘りできる補助メモとして使います。',
    ],
    meetings: [
      '過去の面談や会議から学んだポイントを再利用しやすい形で保存しています。',
      '次回に活かせる観点や、相手ごとの傾向を引き出すためのメモです。',
      '振り返りと準備の橋渡しになる情報を優先して残しています。',
    ],
    todos: [
      '次回までに確認したいことや準備したいことをまとめたタスクメモです。',
      '会話の前後で抜け漏れが起きないよう、行動レベルの粒度で管理します。',
      '直近の予定や相手情報と一緒に参照される前提です。',
    ],
    experiences: [
      '話せる経験をエピソード単位で整理した下地データです。',
      '課題・行動・結果・学びの流れで会話に載せやすい形にしています。',
      '面接だけでなく、会議や1on1でも使える再現可能な経験を優先しています。',
    ],
  };

  return (
    fallbackMap[title] ?? [
      `${title} の内容を会話で使える形に整理するための読み込み項目です。`,
      '要点、数字、背景、次に話したいことを追記していく前提のプレースホルダーです。',
      'ローカルで保持しながら、必要なときだけ参照できるようにしています。',
    ]
  );
}
